const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
function setup(page='index.html',seed={}){
 const map=new Map(Object.entries(seed)),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)};
 const location={pathname:'/taxfly/'+page,search:'',href:'',replace(value){this.href=value}};
 const window={location},document={currentScript:{src:'https://example.test/taxfly/assets/app-routes.js'}};
 const context={window,document,location,localStorage:storage,URL,URLSearchParams};vm.runInNewContext(read('assets/app-routes.js'),context);
 return{context,routes:window.TaxflyRoutes,map,location};
}
test('selector Europa lleva directamente al dashboard dentro de TaxEurope',()=>{const s=read('selector.html');assert.match(s,/class="region-card card-europe" href="TaxEurope\/index.html"/);assert.match(s,/taxfly_destino','europe'/);assert.ok(fs.existsSync(path.join(root,'TaxEurope/index.html')))});
test('Switch app funciona desde USA y Europa sin duplicar el prefijo del proyecto',()=>{for(const page of ['index.html','compras.html','TaxEurope/index.html','TaxEurope/tickets.html']){const f=setup(page,{taxusa_pending_redirect:'compras.html'});f.routes.enter('europe');assert.equal(f.location.href,'https://example.test/taxfly/TaxEurope/index.html');assert.equal(f.map.get('taxfly_destino'),'europe');assert.equal(f.map.has('taxusa_pending_redirect'),false);f.routes.enter('usa');assert.equal(f.location.href,'https://example.test/taxfly/index.html');assert.equal(f.map.get('taxfly_destino'),'usa')}});
test('identidad de cada app proviene de su carpeta, incluso con ambas abiertas',()=>{assert.equal(setup('index.html',{taxfly_destino:'europe'}).routes.region(),'usa');assert.equal(setup('TaxEurope/index.html',{taxfly_destino:'usa'}).routes.region(),'europe')});
test('login común siempre lleva al selector aunque la última elección fuera Europa',()=>{const source=read('assets/login-app.js');const fn=source.slice(source.indexOf('function goToApp()'),source.indexOf('async function initScreen()'));for(const page of ['login.html','TaxEurope/login.html']){const f=setup(page,{taxfly_destino:'europe'});Object.assign(f.context,{installRequested:false,isOnline:()=>true,hideSplash:fn=>fn()});vm.runInNewContext(fn+'\ngoToApp();',f.context);assert.equal(f.location.href,'https://example.test/taxfly/selector.html')}});
test('enlaces de retorno de login conservan carpeta y rechazan destinos externos',()=>{const f=setup('TaxEurope/login.html');assert.equal(f.routes.destination('tickets.html'),'https://example.test/taxfly/TaxEurope/tickets.html');assert.equal(f.routes.destination('https://evil.test/index.html'),null);assert.equal(f.routes.destination('../index.html'),null);assert.equal(setup('login.html').routes.destination('TaxEurope/planificacion.html'),'https://example.test/taxfly/TaxEurope/planificacion.html')});
test('todos los botones Cambiar app y perfiles usan la ruta común',()=>{for(const folder of ['', 'TaxEurope/']){for(const page of ['tax.html','compras.html','lugares.html','unidades.html','tickets.html','grupo.html']){const html=read(folder+page);assert.ok(html.includes('window.TaxflyRoutes.enter(destino)')||(folder==='TaxEurope/'&&html.includes('id="eu-app-switch"')&&read(folder+'assets/europe-native.js').includes('window.TaxflyRoutes.showSwitcher()')))};assert.ok(read(folder+'assets/index-app.js').includes('window.TaxflyRoutes.enter(d)'));assert.ok(read(folder+'assets/profiles-app.js').includes('window.TaxflyRoutes.home(destino)'));assert.ok(read(folder+'assets/settings.js').includes('window.TaxflyRoutes.showSwitcher()'));assert.ok(read(folder+'assets/rutas-app.js').includes('window.TaxflyRoutes.showSwitcher()'))}});
test('Cambiar app se centra sobre el panel y cierra ajustes antes de abrir',()=>{
 const f=setup('TaxEurope/index.html'),nodes=new Map(),buttons=[];let drawerClosed=false;
 nodes.set('settingsDrawer',{classList:{remove:name=>{drawerClosed=name==='open'}}});nodes.set('menuOverlay',{style:{display:'block'}});
 f.context.document.getElementById=id=>nodes.get(id)||null;
 f.context.document.createElement=tag=>({tag,style:{},append(...children){buttons.push(...children.filter(c=>c.tag==='button'))},addEventListener(){},showModal(){this.open=true},close(){this.open=false}});
 f.context.document.body={append:n=>nodes.set(n.id,n)};f.context.document.head={append:()=>{}};
 f.routes.showSwitcher();const dialog=nodes.get('taxfly-app-switcher');assert.ok(drawerClosed);assert.equal(nodes.get('menuOverlay').style.display,'none');assert.match(dialog.style.cssText,/position:fixed;inset:0;margin:auto/);assert.equal(dialog.open,true);assert.equal(buttons.length,3);buttons[0].onclick();assert.equal(f.location.href,'https://example.test/taxfly/index.html');assert.equal(dialog.open,false);f.routes.showSwitcher();buttons[1].onclick();assert.equal(f.location.href,'https://example.test/taxfly/TaxEurope/index.html');f.routes.showSwitcher();buttons[2].onclick();assert.equal(dialog.open,false);
});
test('no existe formulario de login europeo y todas las sesiones pasan por selector',()=>{
 const alias=read('TaxEurope/login.html');assert.match(alias,/location.replace\('\.\.\/login.html'\+location.search\)/);assert.ok(!alias.includes('<form'));
 const source=read('assets/login-app.js'),fn=source.slice(source.indexOf('function goToApp()'),source.indexOf('async function initScreen()'));
 for(const seed of [{taxfly_destino:'usa'},{taxfly_destino:'europe',taxusa_pending_redirect:'TaxEurope/taxfree.html'},{perfilActivoId:'perfil',taxfly_destino:'europe'}]){const f=setup('login.html',seed);f.context.location.search='?next=TaxEurope/compras.html';Object.assign(f.context,{installRequested:false,hideSplash:callback=>callback()});vm.runInNewContext(fn+'\ngoToApp();',f.context);assert.equal(f.location.href,'https://example.test/taxfly/selector.html');assert.equal(f.map.has('taxusa_pending_redirect'),false)}
});
test('módulos europeos tienen cabecera y ajustes de TaxUSA sin menú lateral propio',()=>{
 for(const page of ['index','compras','tax','taxfree','alojamiento','lugares','planificacion','rutas','grupo','mis-cosas','unidades']){const html=read('TaxEurope/'+page+'.html');assert.match(html,/class="app-header"/);assert.match(html,/id="btnSettings" onclick="toggleSettings\(\)"/);assert.match(html,/class="nav-bar"/);assert.match(html,/src="assets\/settings.js"/);assert.ok(!html.includes('<aside class="eu-sidebar"'))}
 assert.match(read('TaxEurope/assets/europe-chrome.js'),/perfilActivoFoto/);assert.match(read('TaxEurope/assets/europe-chrome.js'),/\.\.\/profiles.html/);
});
